apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Redis
    openshift.io/image.dockerRepositoryCheck: 2019-03-26T12:29:54Z
  creationTimestamp: null
  generation: 1
  name: redis
  selfLink: /apis/image.openshift.io/v1/namespaces/openshift/imagestreams/redis
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Provides a Redis 3.2 database on RHEL 7. For more information about
        using this database image, including OpenShift considerations, see https://github.com/sclorg/redis-container/tree/master/3.2/README.md.
      iconClass: icon-redis
      openshift.io/display-name: Redis 3.2
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: redis
      version: "3.2"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/redis-32-rhel7:latest
    generation: 1
    importPolicy: {}
    name: "3.2"
    referencePolicy:
      type: Local
  - annotations:
      description: |-
        Provides a Redis database on RHEL 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/redis-container/tree/master/3.2/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Redis available on OpenShift, including major versions updates.
      iconClass: icon-redis
      openshift.io/display-name: Redis (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: redis
    from:
      kind: ImageStreamTag
      name: "3.2"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
status:
  dockerImageRepository: docker-registry.default.svc:5000/redis
