apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Python
    openshift.io/image.dockerRepositoryCheck: 2020-02-14T13:58:21Z
    samples.operator.openshift.io/version: 4.2.19
  creationTimestamp: null
  generation: 1
  labels:
    samples.operator.openshift.io/managed: "true"
  name: python
  selfLink: /apis/image.openshift.io/v1/namespaces/openshift/imagestreams/python
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Python 2.7 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/2.7/README.md.
      iconClass: icon-python
      openshift.io/display-name: Python 2.7
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/django-ex.git
      supports: python:2.7,python
      tags: builder,python
      version: "2.7"
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/python-27-rhel7:latest
    generation: 1
    importPolicy: {}
    name: "2.7"
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Python 3.5 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.5/README.md.
      iconClass: icon-python
      openshift.io/display-name: Python 3.5
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/django-ex.git
      supports: python:3.5,python
      tags: hidden,builder,python
      version: "3.5"
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/python-35-rhel7:latest
    generation: 1
    importPolicy: {}
    name: "3.5"
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Python 3.6 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.6/README.md.
      iconClass: icon-python
      openshift.io/display-name: Python 3.6
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/django-ex.git
      supports: python:3.6,python
      tags: builder,python
      version: "3.6"
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/python-36-rhel7:latest
    generation: 1
    importPolicy: {}
    name: "3.6"
    referencePolicy:
      type: Local
  - annotations:
      description: |-
        Build and run Python applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.6/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Python available on OpenShift, including major version updates.
      iconClass: icon-python
      openshift.io/display-name: Python (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/django-ex.git
      supports: python
      tags: builder,python
    from:
      kind: ImageStreamTag
      name: "3.6"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/python
